name: Docker
on:
  push:
    branches: [ "ci" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "ci" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: ${{ env.IMAGE_NAME }}
        registry: ${{ env.REGISTRY }}
        githubOrg: override-org # optional
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
        dockerfile: Dockerfile
